### ISSUE TITLE
Potential issue with DNS propagation checks for domain with `-`

### ISSUE THREAD

**Issue by leandrotoledo** [gregtwallace/certwarden-backend#9]
Hi @gregtwallace,

First of all, thank you for this amazing project! It was recommended to me on Reddit and it's exactly what I was looking for my home lab.

I've been using it throughout the weekend and have had plenty of success issuing certificates (my domain is managed by Cloudflare, and I'm using the `dns01cloudflare` provider).

However, I'm encountering an issue with one particular domain, `adguard-backup.mydomain.com`. After a few attempts to place an order, I see the following in the logs:

```
12/29/2024, 8:05:18 PM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.adguard-backup.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 1m48.1s
12/29/2024, 8:03:35 PM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.adguard-backup.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 1m42.5s
12/29/2024, 8:01:56 PM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.adguard-backup.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 1m38.7s
12/29/2024, 7:59:50 PM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.adguard-backup.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 2m6s
```

Despite these checks, the order eventually fails silently with no certificate issued. In the Certificate view, the ACME Order status remains "Pending."

It's worth mentioning that I can successfully obtain a certificate for this same domain using acme.sh, so the issue seems specific to `dns_checker`.

I'll enable more verbose debug logs and report back with further findings. I wanted to give you a heads up in case this points to a potential issue with DNS propagation checks or something specific to the domain name format. Or maybe I'm missing something obvious here...

Thank you!

**Comment by gregtwallace** [comment]
Strange. The dns checker package actually runs for any dns provider (if I recall correctly offhand). 

Ate you using the default dns services (Cloudflare, quad9, and google) for dns checker? It might have been a transient dns propagation issue or something. I’m not sure how long you were fiddling with it. 

Essentially those log messages are just Cert Warden doing dns queries to those services until each returns the expected record. The message seems to be indicating 2 eventually get the record but the 3rd doesn’t before timeout.

**Comment by leandrotoledo** [comment]
Thanks for the prompt reply. It looks like after a few more attempts it
issued the certificate for this domain.

I'm not exactly sure what could have happened. But I can reopen if I run
into any issues again with some more context and logs to let you know.

Thanks again for your help!

**Comment by gregtwallace** [comment]
Can you check how long it was trying for in the logs? I checked the function and it should be trying for up to 30 minutes which should be more than enough time. I suppose I could bump it up to an hour though. 

It would be nice to confirm it tried the full 30 minutes though. 

https://github.com/gregtwallace/certwarden-backend/blob/9d8eb951e74629271a0d717ea08cf23c52777256/pkg/challenges/dns_checker/check_types.go#L35

**Comment by leandrotoledo** [comment]
It seems to be working as intended within the 30-minute limit. I'll let you know if it happens again. Thanks!

```
12/31/2024, 10:17:43 AM, info, orders/fulfilling_do.go:216, orders: fulfilling worker 2: order id 13 completed with status valid (certificate name: semaphore.mydomain.com, subject: semaphore.mydomain.com)
12/31/2024, 10:15:32 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 1m54.4s
12/31/2024, 10:14:03 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 1m29.1s
12/31/2024, 10:12:36 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 1m26.7s
12/31/2024, 10:11:32 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 1m4.3s
12/31/2024, 10:10:32 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 59.5s
12/31/2024, 10:09:49 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 43.1s
12/31/2024, 10:09:15 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 33.7s
12/31/2024, 10:08:41 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 33.6s
12/31/2024, 10:08:12 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 29.2s
12/31/2024, 10:07:52 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 2 (67%, min: 100%), will check again in 19.5s
12/31/2024, 10:07:33 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 1 (33%, min: 100%), will check again in 19.3s
12/31/2024, 10:07:19 AM, info, dns_checker/check_types.go:41, dns_checker: check _acme-challenge.semaphore.mydomain.com: propagated: 0 (0%, min: 100%), will check again in 13.6s
12/31/2024, 10:07:18 AM, info, orders/fulfilling_do.go:24, orders: fulfilling worker 2: ordering order id 13 (certificate name: semaphore.mydomain.com, subject: semaphore.mydomain.com)
```
